# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protogen.audiostream import audiostream_pb2 as audiostream_dot_audiostream__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audiostream/audiostream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioStreamerServiceStub(object):
    """python -m grpc_tools.protoc -Iproto --python_out=protogen --pyi_out=protogen --grpc_python_out=protogen proto/audiostream/audiostream.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/audiostream.AudioStreamerService/StreamAudio',
                request_serializer=audiostream_dot_audiostream__pb2.AudioChunk.SerializeToString,
                response_deserializer=audiostream_dot_audiostream__pb2.Acknowledgement.FromString,
                _registered_method=True)


class AudioStreamerServiceServicer(object):
    """python -m grpc_tools.protoc -Iproto --python_out=protogen --pyi_out=protogen --grpc_python_out=protogen proto/audiostream/audiostream.proto
    """

    def StreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioStreamerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=audiostream_dot_audiostream__pb2.AudioChunk.FromString,
                    response_serializer=audiostream_dot_audiostream__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audiostream.AudioStreamerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audiostream.AudioStreamerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioStreamerService(object):
    """python -m grpc_tools.protoc -Iproto --python_out=protogen --pyi_out=protogen --grpc_python_out=protogen proto/audiostream/audiostream.proto
    """

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/audiostream.AudioStreamerService/StreamAudio',
            audiostream_dot_audiostream__pb2.AudioChunk.SerializeToString,
            audiostream_dot_audiostream__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
